name: Convert Markdown to HTML

on:
  push:
    branches:
      - "**"
      - "!docs" # Exclude docs branch to avoid circular triggers
    paths:
      - "**/*.md" # Only trigger on markdown file changes

jobs:
  convert-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper branch handling

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 pygments
          npm init -y
          npm install markdown-it markdown-it-highlightjs highlight.js markdown-it-anchor markdown-it-toc-done-right

      - name: List files in workflow directory
        run: |
          echo "Files in .github/workflows directory:"
          ls -la .github/workflows/

      - name: Run Python conversion script
        run: python .github/workflows/md_converter.py
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
